server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:30157/bouncer?sslmode=disable
    user: root
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    test-on-borrow: true
    max-wait: 10000
    max-active: 50
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    hibenrate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

