server:
  port: 8000
db:
  username: None
  password: What?
hazelcast:
  ip: 192.168.99.100
  port: 31267
  user: herolynx
  pass: pass
spring:
  datasource:
    url: jdbc:postgresql://cockroachdb:26257/bouncer?sslmode=disable
    user: root
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    test-on-borrow: true
    max-wait: 10000
    max-active: 50
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibenrate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

