apiVersion: v1
kind: ConfigMap
metadata:
  name: bouncer
  namespace: default
data:
  application.properties: |
    spring.cloud.kubernetes.secrets.paths=/etc/secrets/postgres-secrets
    ping.message: Greetings K8s fans!
