apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: hazelcast
  labels: 
    name: hazelcast
spec:
  revisionHistoryLimit: 1
  replicas: 3
  template: 
    metadata: 
      labels: 
        name: hazelcast
    spec: 
      containers: 
      - name: hazelcast
        image: quay.io/pires/hazelcast-kubernetes:3.8.3
        imagePullPolicy: Always
        env:
        - name: "DNS_DOMAIN"
          value: "cluster.local"
        - name: "HC_GROUP_NAME"
          value: "herolynx"
        - name: "HC_GROUP_PASSWORD"
          value: "pass"
        - name: "HC_REST_ENABLED"
          value: "true"
        ports:
        - name: hazelcast
          containerPort: 5701
