apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: hazelcast
  name: hazelcast
spec: 
  ports:
    - port: 5701
      protocol: TCP
      targetPort: 5701
      name : http
  selector: 
    name: hazelcast
  type: LoadBalancer
